### ISSUE TITLE
obtain alignment/attention information

### ISSUE THREAD

**Issue by lhk** [pytorch/translate#694]
I would like to access information on alignment or even the full attention matrix. This is possible with the fairseq CLI (with the `print-alignment` flag) and to some extent also in the python interface to fairsec (as logging messages).
Is there a way to obtain this information with pytorch-translate?

**Comment by jmp84** [comment]
Hi @lhk, please use https://github.com/pytorch/fairseq instead of Translate as Translate is deprecated (see announcement at the top of the README in https://github.com/pytorch/translate). We are developing some Translate features such as TorchScript directly in fairseq. If you have any questions or feature requests, please raise an issue directly in https://github.com/pytorch/fairseq
